import type { Metadata } from "next";
import { Cairo, Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider"
import Header from "@/components/Home/header/Index";
import Footer from "@/components/ui/Footer";
import { ReduxProvider } from "@/providers/ReduxProvider";
import { Locale } from "@/i18n.config";
import { Directions, Languages } from "@/constants/enums";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";
import NextAuthSessionProvider from "@/providers/NextAuthSessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  preload: true,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  preload: true,
});

const cairo = Cairo({
  subsets: ["latin"],
  preload: true,
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: Locale }>
}>) {
  const locale = (await params).locale
  return (
    <html
      lang={locale}
      dir={locale === Languages.ARABIC ? Directions.RTL : Directions.LTR}
      suppressHydrationWarning>
      <body
        className={locale === Languages.ARABIC ? cairo.className : `${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          themes={["dark", "light"]}
          enableSystem
          disableTransitionOnChange
        >
          <NextAuthSessionProvider>

            <ReduxProvider>
              <Header />
              {children}
              <Footer />
              <Toaster />
            </ReduxProvider>

          </NextAuthSessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
